### ISSUE TITLE
Support for Ivy

### ISSUE THREAD

**Issue by techn1fire** [zoomsphere/ngx-store#81] opened 2019-11-14 05:21 UTC
Support Ivy please

**Error:**
`ERROR in node_modules/ngx-store/src/ngx-store.d.ts:7:22 - error TS-996002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

7 export declare class WebStorageModule {
                       ~~~~~~~~~~~~~~~~

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
ℹ ｢wdm｣: Failed to compile.`

========================
**Environment:**
`Angular CLI: 8.3.19
Node: 12.9.1
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.19
@angular-devkit/build-angular     0.803.19
@angular-devkit/build-optimizer   0.803.19
@angular-devkit/build-webpack     0.803.19
@angular-devkit/core              8.3.19
@angular-devkit/schematics        8.3.19
@angular/cdk                      8.2.3
@angular/cli                      8.3.19
@angular/fire                     5.2.3
@angular/material                 8.2.3
@angular/youtube-player           8.2.3
@ngtools/webpack                  8.3.19
@schematics/angular               8.3.19
@schematics/update                0.803.19
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2`

**Comment by alessiostalla** [comment] 2019-12-15 19:49
I get that on Angular 9 RC 6, too.

**Comment by mtraynham** [comment] 2020-02-07 12:48
This is now a blocker for me upgrading to Angular 9.  Is this potentially related to using rollup instead of angular's own build system (e.g. ng-packagr)?

**Comment by Taylorsuk** [comment] 2020-02-07 15:37
I can confirm that this is still an issue with Angular 9 official release.
```
Failed to compile.

node_modules/ngx-store/src/ngx-store.d.ts:7:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

7 export declare class WebStorageModule {
```
I've compared `ngx-store.d.ts` to other packages and it seems that it's not doing anything different. Any ideas?

**Comment by mtraynham** [comment] 2020-02-07 17:39
I created an issue repo, https://github.com/mtraynham/ngx-store-issue81

- First commit was generated with `ng new ngx-storage-issue81`
- [Second commit](https://github.com/mtraynham/ngx-store-issue81/commit/1445797ad37560692f829fb72490f1b28e1dede0) adds `ngx-store` as a dependency and includes it in the `app.module.ts`

Run `ng build` and you get the following error as mentioned in the issue.
```
$ ng build

Compiling @angular/core : es2015 as esm2015

Compiling @angular/common : es2015 as esm2015

Compiling @angular/platform-browser : es2015 as esm2015

Compiling @angular/platform-browser-dynamic : es2015 as esm2015

Compiling ngx-store : es2015 as esm2015

Compiling @angular/router : es2015 as esm2015

ERROR in node_modules/ngx-store/src/ngx-store.d.ts:7:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

7 export declare class WebStorageModule {
                       ~~~~~~~~~~~~~~~~
```

I'm wondering if this project could benefit moving to the workspace-library style builds that Angular supports, https://angular.io/guide/creating-libraries, in leu of this rollup/build.js style.

**Comment by alessiostalla** [comment] 2020-02-26 09:19
Any update? For me with Ivy this compiles fine, but at runtime I get:
Error: "Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping."

And by debugging I see the offending service is LocalStorageService.

**Comment by Vaelor** [comment] 2020-03-05 15:23
So, this is highly experimental and might contain errors, since I did not get the tests running and such.
I tried to move the library from rollup to the angular library style which wasn't so hard (the diff is huge though, because a lot of files where moved etc).

If anyone wants to have a look, maybe fix some other stuff... In my case the resulting build worked with the test repository provided here https://github.com/zoomsphere/ngx-store/issues/81#issuecomment-583520358

But without working tests it is hard to guarantee that everything works as intended.

https://github.com/Vaelor/ngx-store
Keep in mind, I do not intend to support that offically/continue it/publish an npm package etc. So please don't get your hopes up ;-)

I probably won't have much time to make this work properly, but maybe this is a start that someone can use to further improve that... But I guess it is still quite a bit of work.
Oh and it breaks compatibility with the old ViewEngine and only works in ivy projects, because trying to build with `--prod` doesn't work because of circular imports.

Aside from mostly moving files, I had to change the lodash imports because these wouldn't work anymore in the old form.

**Comment by mtraynham** [comment] 2020-03-13 13:27
Thanks for doing that @Vaelor.  I can take a look today and may offer a PR to your repo if it needs corrections.  Hopefully we could just create a PR back here to get that merged and @DanielKucal can chime in sometime.

Worse comes to worse, we could always create a second Git branch with the dist/ code published to Git, create a second PR back here with the intention of it not getting merged and then users could point to the PR reference in their package.json files.  This is nice because Github keeps PR branches around forever and they won't break if somebody closes the PR or deletes the branch.  I think you would do something like:

```
"dependencies": {
    "ngx-store": "zoomsphere/ngx-store#pull/129/head"
}
```

**Comment by GerkinDev** [comment] 2020-03-27 18:10
Plz do that, so that we could do code reviews & further commits while still on this repo

**Comment by beleta** [comment] 2020-03-30 14:23
I found a way to build a project that uses ngx-store with Angular 9.

I am using CodeMix that is an Eclipse plugin that is used to develop Angular projects, among others.

It uses a package angular-ide that provides a modified `ng` command that is run instead of the ng provided by angular when used inside a Codemix provided terminal inside Eclipse.

If you install angular-ide this modified `ng` can be run using the following command: `node_modules/angular-ide/bin/ng` .

If I use this ng, even outside Eclipse, to build my project that uses ngx-store it builds with no problem. 

I asked Codemix developers for an explanation of this behavior that I'll post here when I receive an answer.

**Comment by beleta** [comment] 2020-03-30 17:20
After inspecting the angular-ide ng command it seems that simply disables Ivy.

**Comment by jan-moxter** [comment] 2020-04-01 03:51
Hi,
I did work on this a little bit :-) I got a working ngx-store witch works with ivy for angular 9 done in my fork. Feel free to check out https://github.com/jan-moxter/ngx-store/

I am thinking to do a pull request if my approach is OK ... it is a very big change!

For the ones that are in a hurry you can install it via:

`npm install https://github.com/jan-moxter/ngx-store/releases/download/3.0.0/ngx-store-3.0.0.tgz`

**Comment by jan-moxter** [comment] 2020-04-02 22:43
So the question for me is in the moment @DanielKucal  is this you are something interested in? There seems to not have been much movement lately :-) I can very easy produce a pull request.... I would remove the commits that I used to figure out if I could use the npm from github directly

**Comment by GerkinDev** [comment] 2020-04-06 21:52
Seeing the absence of activity from the repo owner in the last 6 months, I'm starting to think that something happened to him.
@jan-moxter I'll try your lib & do some feedbacks/tests if I have time. Thank you very much for the installable version ;)

DanielKucal I hope you're doing well. Take care

> PS: I did voluntarily not mentioned DanielKucal to avoid too much `@mention`s spamming.

**Comment by jan-moxter** [comment] 2020-04-06 23:01
Thanks. I do have the same thoughts....input is really appreciated. I am going to wait a couple of days more and if I see nothing new, will go with releasing it as a new package

**Comment by beleta** [comment] 2020-04-07 06:20
Thanks a lot @jan-moxter for your work!

**Comment by jan-moxter** [comment] 2020-04-10 22:19
Hello 
@nanijnv1 also did work on it https://github.com/nanijnv1/ngx-store   but he took a different approach by only altering some stuff in package.json. I went for changing it into a angular library project :-)  His version is already on npm as https://www.npmjs.com/package/ngx-store-9 

Feel free to check out that version

**Comment by beleta** [comment] 2020-04-12 06:37
Don't forget 

> Hello
> @nanijnv1 also did work on it https://github.com/nanijnv1/ngx-store but he took a different approach by only altering some stuff in package.json. I went for changing it into a angular library project :-) His version is already on npm as https://www.npmjs.com/package/ngx-store-9
> 
> Feel free to check out that version

Don't forget to install this package using this command:

`npm i ngx-store@npm:ngx-store-9`

if you want to keep your code unmodified or if you use libraries that use ngx-store.

**Comment by beleta** [comment] 2020-04-12 07:01
ngx-store-9 give the following error that I report here because I cannot report a new issue in the project.

```
ERROR in Unexpected value 'WebStorageModule in /Users/beleta/eclipse-workspace/CarverConsumosAngular/node_modul
es/ngx-store/src/ngx-store.d.ts' imported by the module 'AppModule in /Users/beleta/eclipse-workspace/CarverCon
sumosAngular/src/app/app.module.ts'. Please add a @NgModule annotation.

```

**Comment by beleta** [comment] 2020-04-12 07:11
> Hi,
> I did work on this a little bit :-) I got a working ngx-store witch works with ivy for angular 9 done in my fork. Feel free to check out https://github.com/jan-moxter/ngx-store/
> 
> I am thinking to do a pull request if my approach is OK ... it is a very big change!
> 
> For the ones that are in a hurry you can install it via:
> 
> `npm install https://github.com/jan-moxter/ngx-store/releases/download/3.0.0/ngx-store-3.0.0.tgz`

I tried your package after installing it with this command:

`npm install ngx-store@https://github.com/jan-moxter/ngx-store/releases/download/3.0.0/ngx-store-3.0.0.tgz`

And I got this error message:

`ERROR in Encountered undefined provider! Usually this means you have a circular dependencies. This might be caused by using 'barrel' index.ts files.`

That doesn't show when using the original package.

**Comment by beleta** [comment] 2020-04-15 10:25
> Hello
> @nanijnv1 also did work on it https://github.com/nanijnv1/ngx-store but he took a different approach by only altering some stuff in package.json. I went for changing it into a angular library project :-) His version is already on npm as https://www.npmjs.com/package/ngx-store-9
> 
> Feel free to check out that version

I putted here the problems I encountered because your project doesn't admit issues.

**Comment by jan-moxter** [comment] 2020-04-16 03:31
Did you have the chance to try the version I mention above? It is already in npm

**Comment by beleta** [comment] 2020-04-16 20:32
As I already said I tried the tgz file. What's the name of your npm project?

**Comment by jan-moxter** [comment] 2020-04-16 20:34
Not mine. :-) I am talking about https://github.com/nanijnv1/ngx-store he release it to  https://www.npmjs.com/package/ngx-store-9

**Comment by beleta** [comment] 2020-04-16 20:37
> ngx-store-9 give the following error that I report here because I cannot report a new issue in the project.
> 
> ```
> ERROR in Unexpected value 'WebStorageModule in /Users/beleta/eclipse-workspace/CarverConsumosAngular/node_modul
> es/ngx-store/src/ngx-store.d.ts' imported by the module 'AppModule in /Users/beleta/eclipse-workspace/CarverCon
> sumosAngular/src/app/app.module.ts'. Please add a @NgModule annotation.
> ```

Yes I did so, as I said in the quoted reply.

**Comment by jan-moxter** [comment] 2020-04-17 02:18
Sorry did not get that. I tried both libraries in the project where I need it.... and both work without any issues. Can you provide the example where it does lead to the mentioned errors?

**Comment by beleta** [comment] 2020-04-17 17:01
If you provide me a private mail I can send my projects

**Comment by ServerSports** [comment] 2020-04-28 14:02
@jan-moxter i tried both libraries 

```
https://www.npmjs.com/package/ngx-store-9
npm install ngx-store@https://github.com/jan-moxter/ngx-store/releases/download/3.0.0/ngx-store-3.0.0.tgz
```

And we get the same errors that @beleta. This is my environment:

`Angular CLI: 9.1.3
Node: 12.16.1
OS: win32 x64

Angular: 9.1.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: No

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.23
@angular-devkit/build-angular      0.901.3
@angular-devkit/build-optimizer    0.901.3
@angular-devkit/build-webpack      0.901.3
@angular-devkit/core               8.3.23
@angular-devkit/schematics         8.3.23
@angular/cdk                       9.2.1
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.2.1
@angular/material-moment-adapter   9.2.1
@ngtools/webpack                   9.1.3
@schematics/angular                8.3.23
@schematics/update                 0.901.3
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0`

**Comment by jan-moxter** [comment] 2020-04-28 15:11
thanks for the input. got a project you could share to be able to debug?

**Comment by ServerSports** [comment] 2020-04-28 15:23
Provide me a private mail, please

**Comment by jan-moxter** [comment] 2020-04-28 15:37
:-)  tried this before and it seems to not have worked...... how can I provided my email to you ??

**Comment by ServerSports** [comment] 2020-04-28 15:43
You can add a email to the project or in your user profile

**Comment by jan-moxter** [comment] 2020-04-28 17:03
added

**Comment by jan-moxter** [comment] 2020-04-28 22:45
Hello guys, with the help of ServerSports and some try and error we think we figured out the issue.

https://github.com/jan-moxter/ngx-store/releases/download/3.0.3/ngx-store-3.0.3.tgz

seems to work now. Planing to do a release on npm for this version then

**Comment by jan-moxter** [comment] 2020-04-29 00:25
I released my version to npm as part of my org :-) 
 `npm i @efaps/ngx-store`

Also activated issues in https://github.com/eFaps/ngx-store

**Comment by wunaidage** [comment] 2020-05-27 18:35
> Any update? For me with Ivy this compiles fine, but at runtime I get:
> Error: "Angular JIT compilation failed: '@angular/compiler' not loaded!
> 
> * JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
> * Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
> * Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping."
> 
> And by debugging I see the offending service is LocalStorageService.

I see the same issue, and I upgraded all my dependencies to latest version. since only ngx-store does not upgrade, I guess ngx-store does not compatible with angular 9.

**Comment by jan-moxter** [comment] 2020-05-27 18:39
this version of ngx-store seems to be "dead"  in the moment.
Therefore the release from a fork and putting it into a namespace:  https://github.com/eFaps/ngx-store -> npm i @efaps/ngx-store

**Comment by DanielKucal** [comment] 2021-07-31 13:18
Latest version supports Ivy.

**Closed as completed by DanielKucal** 2021-07-31 13:18 UTC
