### ISSUE TITLE
localStorage is not defined (Angular Universal)

### ISSUE THREAD

**Issue by rreddyNg** [zoomsphere/ngx-store#42] opened 2018-04-12 02:42 UTC
Hi Dan, when I compile my project with angular universal, I get this error:

`ConfigHelper._webStorageUtility = new__WEBPACK_IMPORTED_MODULE_0__utility_webstorage_utility__["a" /* WebStorageUtility */](localStorage, CONFIG_PREFIX); `

`ReferenceError: localStorage is not defined`

**Comment by DanielKucal** [comment] 2018-04-17 08:53
Duplicate of https://github.com/zoomsphere/ngx-store/issues/18

**Closed as completed by DanielKucal** 2018-04-17 08:53 UTC
